name: sick readme

on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  cinco:
    name: do the do do do do :) 
    runs-on: ubuntu-latest
    steps:
      - name: check it out
        uses: actions/checkout@v2
        
      - name: Set timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d %H:%M:%S')"

      - name: do the do do do do do lol
        env:
          GITHUB_TOKEN: ${{ secrets.LINO_TOKEN }}
        run: ./readmeScript.sh

      - name: add the things
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git pull --ff-only && \
          git diff --quiet --exit-code || git commit -am "${GITHUB_SHA} - ${{ steps.timestamp.outputs.timestamp }}" && \
          git push
