name: sick readme

on:
  schedule:
    - cron: "*/720 * * * *"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  cinco:
    name: do the do do do do :) 
    runs-on: ubuntu-latest
    steps:
      - name: check it out
        uses: actions/checkout@v2
        
      # - name: Set timestamp
      #   id: timestamp
      #   run: echo "timestamp=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      # - name: do the do do do do do lol
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.LINO_TOKEN }}
      #   run: ./readmeScript.sh

      #     - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: pip
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run Scraper
        env: 
          NEWS_TOKEN: ${{ secrets.NEWS_TOKEN }}
        run: |
          python fetch.py

      - name: push to origin master
        run: |
          echo start push
          git config --global user.name "0xlino"
          git config --global user.email "hello@benline.co.uk"
            
          git add -A
          git commit -m $(date '+%Y-%m-%d')
          git push
